version: '3'
services:
  my-react-app:
    image: jakiedevops/knovator
    container_name: my-project-app-container
    ports:
      - "3000:80"

  nginx-reverse-proxy:
    image: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my-react-app
